---
# tasks file for WORDPRESS
- name: CREATING DIRECTORY IF THERE IS NO
  file:
    path: /var/www/html/blog/wordpress
    state: directory
    mode: '755'
    owner: nginx
    group: nginx
    recurse: yes

- name: RECURSSIVE PERMISSION FOR WORDPRESS
  command: sudo chown -R nginx:nginx /var/www/html/blog/wordpress
  notify: DISABLED SELinux

- name: ADD GROUP WORDPRESS
  group: name=wordpress

- name: ADD USER WORDPRESS
  user: name=wordpress group=wordpress home=/var/www/html/blog/wordpress/

- name: DOWNLOAD WORDPRESS
  get_url:
    url: https://wordpress.org/wordpress-5.3.tar.gz
    dest: /var/www/html/blog

- name: EXTRACTING FILE WORDPRESS
  unarchive:
    src: /var/www/html/blog/wordpress-5.3.tar.gz
    dest: /var/www/html/blog
    remote_src: yes

#- name: COPY WORDPRESS CONFIGURATION FILE
#  template: src=wp-config.php dest=/var/www/html/blog/wordpress

- name: CHANGE OWNERSHIP OF WORDPRESS INSTALLATION
  file: path=/var/www/html/blog/wordpress/ owner=nginx group=nginx state=directory recurse=yes setype=httpd_sys_content_t

- name: RECURSSIVE PERMISSION FOR WORDPRESS
  command: sudo chown -R nginx:nginx /var/www/html/blog/wordpress

#- name: install SEManage
#  yum: pkg=policycoreutils-python state=present

#- name: set the SELinux policy for the Wordpress directory
#  command: semanage fcontext -a -t httpd_sys_content_t "/srv/wordpress(/.*)?"

#- name: set the SELinux policy for wp-config.php
#  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/wordpress/wp-config\.php"

#- name: set the SELinux policy for wp-content directory
#  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/wordpress/wp-content(/.*)?"

#- name: set the SELinux policy for the *.php files
#  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/wordpress/.*\.php"

#- name: set the SELinux policy for the Upgrade directory
#  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/wordpress/wp-content/upgrade(/.*)?"

#- name: set the SELinux policy for the Uploads directory
#  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/wordpress/wp-content/uploads(/.*)?"

#- name: set the SELinux policy for the wp-includes php files
#  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/wordpress/wp-includes/.*\.php"

#- name: set the SELinux on all the Files
#  command: restorecon -Rv /srv/wordpress

#- name: Start php-fpm Service
#  service: name=php-fpm state=started enabled=yes
